FROM python:3.11.8-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends && \
    pip install --upgrade pip && \
    apt-get clean

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

ENV RABBITMQ_URL="."
ENV QUEUE='.'
ENV TELEGRAM_BOT_TOKEN=''


EXPOSE 8010

CMD ["python", "bot.py"]